apiVersion: v1
kind: Pod
metadata:
  name: limited-pod
  namespace: dev-ns
spec:
  containers:
    - name: busybox-container
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      resources:
        requests:
          memory: "128Mi" #Mebibyte 
          cpu: "100m" #CPU 10%
        limits:
          memory: "256Mi" #Mebibyte 
          cpu: "200m" #CPU 20%
