apiVersion: v1
kind: Pod
metadata:
  name: pizza-pod
spec:
  containers:
    - name: pizza-container
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      envFrom:
        - configMapRef:
            name: pizza-config
        - secretRef:
            name: pizza-secret